/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const TenantStatus = IDL.Variant({
  'trial' : IDL.Null,
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'suspended' : IDL.Null,
});
export const AdminTenantView = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'approvalCode' : IDL.Text,
  'subscriptionStatus' : TenantStatus,
  'shopName' : IDL.Text,
  'cashPaidNote' : IDL.Text,
  'subscriptionExpiresAt' : IDL.Opt(Timestamp),
  'phone' : IDL.Text,
  'trialEndsAt' : Timestamp,
  'cashPaidAt' : IDL.Opt(Timestamp),
});
export const ActivationSlotView = IDL.Record({
  'code' : IDL.Text,
  'claimed' : IDL.Bool,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const CreateInvoiceArgs = IDL.Record({
  'issueDate' : Timestamp,
  'gstEnabled' : IDL.Bool,
  'dueDate' : Timestamp,
  'patientName' : IDL.Text,
  'gstPercentage' : IDL.Opt(IDL.Nat),
  'services' : IDL.Vec(ServiceItem),
});
export const InvoiceId = IDL.Nat;
export const InvoiceStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'paid' : IDL.Null,
  'sent' : IDL.Null,
  'draft' : IDL.Null,
});
export const InvoiceView = IDL.Record({
  'id' : InvoiceId,
  'issueDate' : Timestamp,
  'status' : InvoiceStatus,
  'total' : IDL.Nat,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'gstEnabled' : IDL.Bool,
  'dueDate' : Timestamp,
  'gstAmount' : IDL.Nat,
  'updatedAt' : Timestamp,
  'patientName' : IDL.Text,
  'gstPercentage' : IDL.Opt(IDL.Nat),
  'services' : IDL.Vec(ServiceItem),
});
export const PracticeSettingsView = IDL.Record({
  'owner' : UserId,
  'practiceName' : IDL.Text,
  'updatedAt' : Timestamp,
  'address' : IDL.Text,
});
export const InvoiceFilter = IDL.Record({
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
  'patientName' : IDL.Opt(IDL.Text),
});
export const SavePracticeSettingsArgs = IDL.Record({
  'practiceName' : IDL.Text,
  'address' : IDL.Text,
});
export const UpdateInvoiceArgs = IDL.Record({
  'id' : InvoiceId,
  'issueDate' : Timestamp,
  'status' : InvoiceStatus,
  'gstEnabled' : IDL.Bool,
  'dueDate' : Timestamp,
  'patientName' : IDL.Text,
  'gstPercentage' : IDL.Opt(IDL.Nat),
  'services' : IDL.Vec(ServiceItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'activateWithCode' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'adminApprove' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'adminClearAllTenants' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateActivationSlot' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteTenant' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminExtendTenantExpiry' : IDL.Func(
      [UserId, Timestamp],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'adminGenerateCode' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'rejectedTenants' : IDL.Nat,
          'suspendedTenants' : IDL.Nat,
          'pendingTenants' : IDL.Nat,
          'totalTenants' : IDL.Nat,
          'activeTenants' : IDL.Nat,
          'trialTenants' : IDL.Nat,
          'expiredTenants' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'adminGetTenant' : IDL.Func([UserId], [IDL.Opt(AdminTenantView)], ['query']),
  'adminListSlots' : IDL.Func([], [IDL.Vec(ActivationSlotView)], ['query']),
  'adminListTenants' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(AdminTenantView)],
      ['query'],
    ),
  'adminMarkCashPaid' : IDL.Func(
      [UserId, IDL.Text],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'adminReactivate' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'adminReject' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'adminResetCode' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminSetTenantStatus' : IDL.Func(
      [UserId, TenantStatus],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'adminSuspend' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'adminSuspendAndInvalidate' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'adminToggleSubscription' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'approveTenant' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInvoice' : IDL.Func([CreateInvoiceArgs], [InvoiceView], []),
  'deleteAllInvoices' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteInvoice' : IDL.Func([InvoiceId], [], []),
  'getCallerPracticeSettings' : IDL.Func(
      [],
      [IDL.Opt(PracticeSettingsView)],
      ['query'],
    ),
  'getCallerTenantStatus' : IDL.Func([], [IDL.Opt(TenantStatus)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(InvoiceView)], ['query']),
  'getInvoiceStatusBreakdown' : IDL.Func(
      [],
      [
        IDL.Record({
          'cancelled' : IDL.Nat,
          'paid' : IDL.Nat,
          'sent' : IDL.Nat,
          'draft' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getInvoiceTotalCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPracticeSettings' : IDL.Func(
      [UserId],
      [IDL.Opt(PracticeSettingsView)],
      ['query'],
    ),
  'getRevenueByMonth' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdminPhone' : IDL.Func([], [IDL.Bool], ['query']),
  'listInvoices' : IDL.Func([InvoiceFilter], [IDL.Vec(InvoiceView)], ['query']),
  'registerTenant' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'rejectTenant' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
  'savePracticeSettings' : IDL.Func([SavePracticeSettingsArgs], [], []),
  'updateInvoice' : IDL.Func([UpdateInvoiceArgs], [], []),
  'verifyAndApproveTenant' : IDL.Func(
      [UserId, IDL.Text],
      [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const TenantStatus = IDL.Variant({
    'trial' : IDL.Null,
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const AdminTenantView = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'approvalCode' : IDL.Text,
    'subscriptionStatus' : TenantStatus,
    'shopName' : IDL.Text,
    'cashPaidNote' : IDL.Text,
    'subscriptionExpiresAt' : IDL.Opt(Timestamp),
    'phone' : IDL.Text,
    'trialEndsAt' : Timestamp,
    'cashPaidAt' : IDL.Opt(Timestamp),
  });
  const ActivationSlotView = IDL.Record({
    'code' : IDL.Text,
    'claimed' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const CreateInvoiceArgs = IDL.Record({
    'issueDate' : Timestamp,
    'gstEnabled' : IDL.Bool,
    'dueDate' : Timestamp,
    'patientName' : IDL.Text,
    'gstPercentage' : IDL.Opt(IDL.Nat),
    'services' : IDL.Vec(ServiceItem),
  });
  const InvoiceId = IDL.Nat;
  const InvoiceStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'paid' : IDL.Null,
    'sent' : IDL.Null,
    'draft' : IDL.Null,
  });
  const InvoiceView = IDL.Record({
    'id' : InvoiceId,
    'issueDate' : Timestamp,
    'status' : InvoiceStatus,
    'total' : IDL.Nat,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'gstEnabled' : IDL.Bool,
    'dueDate' : Timestamp,
    'gstAmount' : IDL.Nat,
    'updatedAt' : Timestamp,
    'patientName' : IDL.Text,
    'gstPercentage' : IDL.Opt(IDL.Nat),
    'services' : IDL.Vec(ServiceItem),
  });
  const PracticeSettingsView = IDL.Record({
    'owner' : UserId,
    'practiceName' : IDL.Text,
    'updatedAt' : Timestamp,
    'address' : IDL.Text,
  });
  const InvoiceFilter = IDL.Record({
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
    'patientName' : IDL.Opt(IDL.Text),
  });
  const SavePracticeSettingsArgs = IDL.Record({
    'practiceName' : IDL.Text,
    'address' : IDL.Text,
  });
  const UpdateInvoiceArgs = IDL.Record({
    'id' : InvoiceId,
    'issueDate' : Timestamp,
    'status' : InvoiceStatus,
    'gstEnabled' : IDL.Bool,
    'dueDate' : Timestamp,
    'patientName' : IDL.Text,
    'gstPercentage' : IDL.Opt(IDL.Nat),
    'services' : IDL.Vec(ServiceItem),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'activateWithCode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'adminApprove' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'adminClearAllTenants' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateActivationSlot' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteTenant' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminExtendTenantExpiry' : IDL.Func(
        [UserId, Timestamp],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'adminGenerateCode' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'rejectedTenants' : IDL.Nat,
            'suspendedTenants' : IDL.Nat,
            'pendingTenants' : IDL.Nat,
            'totalTenants' : IDL.Nat,
            'activeTenants' : IDL.Nat,
            'trialTenants' : IDL.Nat,
            'expiredTenants' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'adminGetTenant' : IDL.Func(
        [UserId],
        [IDL.Opt(AdminTenantView)],
        ['query'],
      ),
    'adminListSlots' : IDL.Func([], [IDL.Vec(ActivationSlotView)], ['query']),
    'adminListTenants' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(AdminTenantView)],
        ['query'],
      ),
    'adminMarkCashPaid' : IDL.Func(
        [UserId, IDL.Text],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'adminReactivate' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'adminReject' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'adminResetCode' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminSetTenantStatus' : IDL.Func(
        [UserId, TenantStatus],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'adminSuspend' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'adminSuspendAndInvalidate' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'adminToggleSubscription' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'approveTenant' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInvoice' : IDL.Func([CreateInvoiceArgs], [InvoiceView], []),
    'deleteAllInvoices' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteInvoice' : IDL.Func([InvoiceId], [], []),
    'getCallerPracticeSettings' : IDL.Func(
        [],
        [IDL.Opt(PracticeSettingsView)],
        ['query'],
      ),
    'getCallerTenantStatus' : IDL.Func([], [IDL.Opt(TenantStatus)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(InvoiceView)], ['query']),
    'getInvoiceStatusBreakdown' : IDL.Func(
        [],
        [
          IDL.Record({
            'cancelled' : IDL.Nat,
            'paid' : IDL.Nat,
            'sent' : IDL.Nat,
            'draft' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getInvoiceTotalCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPracticeSettings' : IDL.Func(
        [UserId],
        [IDL.Opt(PracticeSettingsView)],
        ['query'],
      ),
    'getRevenueByMonth' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdminPhone' : IDL.Func([], [IDL.Bool], ['query']),
    'listInvoices' : IDL.Func(
        [InvoiceFilter],
        [IDL.Vec(InvoiceView)],
        ['query'],
      ),
    'registerTenant' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'rejectTenant' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
    'savePracticeSettings' : IDL.Func([SavePracticeSettingsArgs], [], []),
    'updateInvoice' : IDL.Func([UpdateInvoiceArgs], [], []),
    'verifyAndApproveTenant' : IDL.Func(
        [UserId, IDL.Text],
        [IDL.Variant({ 'ok' : AdminTenantView, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };