/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivationSlotView {
  'code' : string,
  'claimed' : boolean,
  'phone' : string,
}
export interface AdminTenantView {
  'id' : UserId,
  'createdAt' : Timestamp,
  'approvalCode' : string,
  'subscriptionStatus' : TenantStatus,
  'shopName' : string,
  'cashPaidNote' : string,
  'subscriptionExpiresAt' : [] | [Timestamp],
  'phone' : string,
  'trialEndsAt' : Timestamp,
  'cashPaidAt' : [] | [Timestamp],
}
export interface CreateInvoiceArgs {
  'issueDate' : Timestamp,
  'gstEnabled' : boolean,
  'dueDate' : Timestamp,
  'patientName' : string,
  'gstPercentage' : [] | [bigint],
  'services' : Array<ServiceItem>,
}
export interface InvoiceFilter {
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'patientName' : [] | [string],
}
export type InvoiceId = bigint;
export type InvoiceStatus = { 'cancelled' : null } |
  { 'paid' : null } |
  { 'sent' : null } |
  { 'draft' : null };
export interface InvoiceView {
  'id' : InvoiceId,
  'issueDate' : Timestamp,
  'status' : InvoiceStatus,
  'total' : bigint,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'gstEnabled' : boolean,
  'dueDate' : Timestamp,
  'gstAmount' : bigint,
  'updatedAt' : Timestamp,
  'patientName' : string,
  'gstPercentage' : [] | [bigint],
  'services' : Array<ServiceItem>,
}
export interface PracticeSettingsView {
  'owner' : UserId,
  'practiceName' : string,
  'updatedAt' : Timestamp,
  'address' : string,
}
export interface SavePracticeSettingsArgs {
  'practiceName' : string,
  'address' : string,
}
export interface ServiceItem {
  'name' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type TenantStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'suspended' : null };
export type Timestamp = bigint;
export interface UpdateInvoiceArgs {
  'id' : InvoiceId,
  'issueDate' : Timestamp,
  'status' : InvoiceStatus,
  'gstEnabled' : boolean,
  'dueDate' : Timestamp,
  'patientName' : string,
  'gstPercentage' : [] | [bigint],
  'services' : Array<ServiceItem>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activateWithCode' : ActorMethod<
    [string, string, string],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'adminApprove' : ActorMethod<
    [UserId],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'adminClearAllTenants' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminCreateActivationSlot' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteTenant' : ActorMethod<
    [UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminExtendTenantExpiry' : ActorMethod<
    [UserId, Timestamp],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'adminGenerateCode' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminGetAllStats' : ActorMethod<
    [],
    {
      'rejectedTenants' : bigint,
      'suspendedTenants' : bigint,
      'pendingTenants' : bigint,
      'totalTenants' : bigint,
      'activeTenants' : bigint,
      'trialTenants' : bigint,
      'expiredTenants' : bigint,
    }
  >,
  'adminGetTenant' : ActorMethod<[UserId], [] | [AdminTenantView]>,
  'adminListSlots' : ActorMethod<[], Array<ActivationSlotView>>,
  'adminListTenants' : ActorMethod<[[] | [string]], Array<AdminTenantView>>,
  'adminMarkCashPaid' : ActorMethod<
    [UserId, string],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'adminReactivate' : ActorMethod<
    [UserId],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'adminReject' : ActorMethod<
    [UserId],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'adminResetCode' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'adminSetTenantStatus' : ActorMethod<
    [UserId, TenantStatus],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'adminSuspend' : ActorMethod<
    [UserId],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'adminSuspendAndInvalidate' : ActorMethod<
    [UserId],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'adminToggleSubscription' : ActorMethod<
    [UserId],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'approveTenant' : ActorMethod<
    [UserId],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInvoice' : ActorMethod<[CreateInvoiceArgs], InvoiceView>,
  'deleteAllInvoices' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'deleteInvoice' : ActorMethod<[InvoiceId], undefined>,
  'getCallerPracticeSettings' : ActorMethod<[], [] | [PracticeSettingsView]>,
  'getCallerTenantStatus' : ActorMethod<[], [] | [TenantStatus]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvoice' : ActorMethod<[InvoiceId], [] | [InvoiceView]>,
  'getInvoiceStatusBreakdown' : ActorMethod<
    [],
    { 'cancelled' : bigint, 'paid' : bigint, 'sent' : bigint, 'draft' : bigint }
  >,
  'getInvoiceTotalCount' : ActorMethod<[], bigint>,
  'getPracticeSettings' : ActorMethod<[UserId], [] | [PracticeSettingsView]>,
  'getRevenueByMonth' : ActorMethod<[], Array<[string, bigint]>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerAdminPhone' : ActorMethod<[], boolean>,
  'listInvoices' : ActorMethod<[InvoiceFilter], Array<InvoiceView>>,
  'registerTenant' : ActorMethod<
    [string, string],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'rejectTenant' : ActorMethod<
    [UserId],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
  'savePracticeSettings' : ActorMethod<[SavePracticeSettingsArgs], undefined>,
  'updateInvoice' : ActorMethod<[UpdateInvoiceArgs], undefined>,
  'verifyAndApproveTenant' : ActorMethod<
    [UserId, string],
    { 'ok' : AdminTenantView } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];