/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InvoiceFilter {
    toDate?: Timestamp;
    fromDate?: Timestamp;
    patientName?: string;
}
export type Timestamp = bigint;
export interface InvoiceView {
    id: InvoiceId;
    issueDate: Timestamp;
    status: InvoiceStatus;
    total: bigint;
    owner: UserId;
    createdAt: Timestamp;
    gstEnabled: boolean;
    dueDate: Timestamp;
    gstAmount: bigint;
    updatedAt: Timestamp;
    patientName: string;
    gstPercentage?: bigint;
    services: Array<ServiceItem>;
}
export type UserId = Principal;
export interface PracticeSettingsView {
    owner: UserId;
    practiceName: string;
    updatedAt: Timestamp;
    address: string;
}
export interface UpdateInvoiceArgs {
    id: InvoiceId;
    issueDate: Timestamp;
    status: InvoiceStatus;
    gstEnabled: boolean;
    dueDate: Timestamp;
    patientName: string;
    gstPercentage?: bigint;
    services: Array<ServiceItem>;
}
export interface ActivationSlotView {
    code: string;
    claimed: boolean;
    phone: string;
}
export interface AdminTenantView {
    id: UserId;
    createdAt: Timestamp;
    approvalCode: string;
    subscriptionStatus: TenantStatus;
    shopName: string;
    cashPaidNote: string;
    subscriptionExpiresAt?: Timestamp;
    phone: string;
    trialEndsAt: Timestamp;
    cashPaidAt?: Timestamp;
}
export type InvoiceId = bigint;
export interface ServiceItem {
    name: string;
    quantity: bigint;
    unitPrice: bigint;
}
export interface CreateInvoiceArgs {
    issueDate: Timestamp;
    gstEnabled: boolean;
    dueDate: Timestamp;
    patientName: string;
    gstPercentage?: bigint;
    services: Array<ServiceItem>;
}
export interface SavePracticeSettingsArgs {
    practiceName: string;
    address: string;
}
export enum InvoiceStatus {
    cancelled = "cancelled",
    paid = "paid",
    sent = "sent",
    draft = "draft"
}
export enum TenantStatus {
    trial = "trial",
    active = "active",
    expired = "expired",
    pending = "pending",
    rejected = "rejected",
    suspended = "suspended"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    activateWithCode(phone: string, code: string, shopName: string): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminApprove(tenantId: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminClearAllTenants(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminCreateActivationSlot(phone: string, code: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteTenant(tenantId: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminExtendTenantExpiry(tenantId: UserId, newExpiresAt: Timestamp): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGenerateCode(phone: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllStats(): Promise<{
        rejectedTenants: bigint;
        suspendedTenants: bigint;
        pendingTenants: bigint;
        totalTenants: bigint;
        activeTenants: bigint;
        trialTenants: bigint;
        expiredTenants: bigint;
    }>;
    adminGetTenant(tenantId: UserId): Promise<AdminTenantView | null>;
    adminListSlots(): Promise<Array<ActivationSlotView>>;
    adminListTenants(search: string | null): Promise<Array<AdminTenantView>>;
    adminMarkCashPaid(tenantId: UserId, note: string): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminReactivate(tenantId: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminReject(tenantId: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminResetCode(phone: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminSetTenantStatus(tenantId: UserId, status: TenantStatus): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminSuspend(tenantId: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminSuspendAndInvalidate(tenantId: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminToggleSubscription(tenantId: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    approveTenant(tenantId: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createInvoice(args: CreateInvoiceArgs): Promise<InvoiceView>;
    deleteAllInvoices(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteInvoice(id: InvoiceId): Promise<void>;
    getCallerPracticeSettings(): Promise<PracticeSettingsView | null>;
    getCallerTenantStatus(): Promise<TenantStatus | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInvoice(id: InvoiceId): Promise<InvoiceView | null>;
    getInvoiceStatusBreakdown(): Promise<{
        cancelled: bigint;
        paid: bigint;
        sent: bigint;
        draft: bigint;
    }>;
    getInvoiceTotalCount(): Promise<bigint>;
    getPracticeSettings(owner: UserId): Promise<PracticeSettingsView | null>;
    getRevenueByMonth(): Promise<Array<[string, bigint]>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerAdminPhone(): Promise<boolean>;
    listInvoices(filter: InvoiceFilter): Promise<Array<InvoiceView>>;
    registerTenant(shopName: string, phone: string): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    rejectTenant(tenantId: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    savePracticeSettings(args: SavePracticeSettingsArgs): Promise<void>;
    updateInvoice(args: UpdateInvoiceArgs): Promise<void>;
    verifyAndApproveTenant(tenantId: UserId, code: string): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AdminTenantView as _AdminTenantView, CreateInvoiceArgs as _CreateInvoiceArgs, InvoiceFilter as _InvoiceFilter, InvoiceId as _InvoiceId, InvoiceStatus as _InvoiceStatus, InvoiceView as _InvoiceView, PracticeSettingsView as _PracticeSettingsView, ServiceItem as _ServiceItem, TenantStatus as _TenantStatus, Timestamp as _Timestamp, UpdateInvoiceArgs as _UpdateInvoiceArgs, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async activateWithCode(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.activateWithCode(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateWithCode(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminApprove(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApprove(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApprove(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminClearAllTenants(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminClearAllTenants();
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminClearAllTenants();
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateActivationSlot(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateActivationSlot(arg0, arg1);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateActivationSlot(arg0, arg1);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteTenant(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteTenant(arg0);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteTenant(arg0);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminExtendTenantExpiry(arg0: UserId, arg1: Timestamp): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminExtendTenantExpiry(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminExtendTenantExpiry(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGenerateCode(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGenerateCode(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGenerateCode(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllStats(): Promise<{
        rejectedTenants: bigint;
        suspendedTenants: bigint;
        pendingTenants: bigint;
        totalTenants: bigint;
        activeTenants: bigint;
        trialTenants: bigint;
        expiredTenants: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllStats();
            return result;
        }
    }
    async adminGetTenant(arg0: UserId): Promise<AdminTenantView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetTenant(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetTenant(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListSlots(): Promise<Array<ActivationSlotView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListSlots();
            return result;
        }
    }
    async adminListTenants(arg0: string | null): Promise<Array<AdminTenantView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListTenants(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListTenants(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminMarkCashPaid(arg0: UserId, arg1: string): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminMarkCashPaid(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminMarkCashPaid(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminReactivate(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminReactivate(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminReactivate(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminReject(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminReject(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminReject(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminResetCode(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetCode(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetCode(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSetTenantStatus(arg0: UserId, arg1: TenantStatus): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetTenantStatus(arg0, to_candid_TenantStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetTenantStatus(arg0, to_candid_TenantStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSuspend(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSuspend(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSuspend(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSuspendAndInvalidate(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSuspendAndInvalidate(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSuspendAndInvalidate(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminToggleSubscription(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminToggleSubscription(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminToggleSubscription(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveTenant(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTenant(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTenant(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createInvoice(arg0: CreateInvoiceArgs): Promise<InvoiceView> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_CreateInvoiceArgs_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_InvoiceView_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_CreateInvoiceArgs_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_InvoiceView_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAllInvoices(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllInvoices();
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllInvoices();
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteInvoice(arg0: InvoiceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async getCallerPracticeSettings(): Promise<PracticeSettingsView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPracticeSettings();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPracticeSettings();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerTenantStatus(): Promise<TenantStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTenantStatus();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTenantStatus();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: InvoiceId): Promise<InvoiceView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoiceStatusBreakdown(): Promise<{
        cancelled: bigint;
        paid: bigint;
        sent: bigint;
        draft: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceStatusBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceStatusBreakdown();
            return result;
        }
    }
    async getInvoiceTotalCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoiceTotalCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoiceTotalCount();
            return result;
        }
    }
    async getPracticeSettings(arg0: UserId): Promise<PracticeSettingsView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPracticeSettings(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPracticeSettings(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueByMonth(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByMonth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByMonth();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerAdminPhone(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdminPhone();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdminPhone();
            return result;
        }
    }
    async listInvoices(arg0: InvoiceFilter): Promise<Array<InvoiceView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices(to_candid_InvoiceFilter_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices(to_candid_InvoiceFilter_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerTenant(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTenant(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTenant(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectTenant(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTenant(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTenant(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async savePracticeSettings(arg0: SavePracticeSettingsArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePracticeSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePracticeSettings(arg0);
            return result;
        }
    }
    async updateInvoice(arg0: UpdateInvoiceArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(to_candid_UpdateInvoiceArgs_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(to_candid_UpdateInvoiceArgs_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyAndApproveTenant(arg0: UserId, arg1: string): Promise<{
        __kind__: "ok";
        ok: AdminTenantView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAndApproveTenant(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAndApproveTenant(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminTenantView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminTenantView): AdminTenantView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceView_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceView): InvoiceView {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TenantStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TenantStatus): TenantStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PracticeSettingsView]): PracticeSettingsView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TenantStatus]): TenantStatus | null {
    return value.length === 0 ? null : from_candid_TenantStatus_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceView]): InvoiceView | null {
    return value.length === 0 ? null : from_candid_InvoiceView_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminTenantView]): AdminTenantView | null {
    return value.length === 0 ? null : from_candid_AdminTenantView_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InvoiceId;
    issueDate: _Timestamp;
    status: _InvoiceStatus;
    total: bigint;
    owner: _UserId;
    createdAt: _Timestamp;
    gstEnabled: boolean;
    dueDate: _Timestamp;
    gstAmount: bigint;
    updatedAt: _Timestamp;
    patientName: string;
    gstPercentage: [] | [bigint];
    services: Array<_ServiceItem>;
}): {
    id: InvoiceId;
    issueDate: Timestamp;
    status: InvoiceStatus;
    total: bigint;
    owner: UserId;
    createdAt: Timestamp;
    gstEnabled: boolean;
    dueDate: Timestamp;
    gstAmount: bigint;
    updatedAt: Timestamp;
    patientName: string;
    gstPercentage?: bigint;
    services: Array<ServiceItem>;
} {
    return {
        id: value.id,
        issueDate: value.issueDate,
        status: from_candid_InvoiceStatus_n20(_uploadFile, _downloadFile, value.status),
        total: value.total,
        owner: value.owner,
        createdAt: value.createdAt,
        gstEnabled: value.gstEnabled,
        dueDate: value.dueDate,
        gstAmount: value.gstAmount,
        updatedAt: value.updatedAt,
        patientName: value.patientName,
        gstPercentage: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.gstPercentage)),
        services: value.services
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    createdAt: _Timestamp;
    approvalCode: string;
    subscriptionStatus: _TenantStatus;
    shopName: string;
    cashPaidNote: string;
    subscriptionExpiresAt: [] | [_Timestamp];
    phone: string;
    trialEndsAt: _Timestamp;
    cashPaidAt: [] | [_Timestamp];
}): {
    id: UserId;
    createdAt: Timestamp;
    approvalCode: string;
    subscriptionStatus: TenantStatus;
    shopName: string;
    cashPaidNote: string;
    subscriptionExpiresAt?: Timestamp;
    phone: string;
    trialEndsAt: Timestamp;
    cashPaidAt?: Timestamp;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        approvalCode: value.approvalCode,
        subscriptionStatus: from_candid_TenantStatus_n4(_uploadFile, _downloadFile, value.subscriptionStatus),
        shopName: value.shopName,
        cashPaidNote: value.cashPaidNote,
        subscriptionExpiresAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.subscriptionExpiresAt)),
        phone: value.phone,
        trialEndsAt: value.trialEndsAt,
        cashPaidAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.cashPaidAt))
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AdminTenantView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AdminTenantView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AdminTenantView_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    paid: null;
} | {
    sent: null;
} | {
    draft: null;
}): InvoiceStatus {
    return "cancelled" in value ? InvoiceStatus.cancelled : "paid" in value ? InvoiceStatus.paid : "sent" in value ? InvoiceStatus.sent : "draft" in value ? InvoiceStatus.draft : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    active: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    suspended: null;
}): TenantStatus {
    return "trial" in value ? TenantStatus.trial : "active" in value ? TenantStatus.active : "expired" in value ? TenantStatus.expired : "pending" in value ? TenantStatus.pending : "rejected" in value ? TenantStatus.rejected : "suspended" in value ? TenantStatus.suspended : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminTenantView>): Array<AdminTenantView> {
    return value.map((x)=>from_candid_AdminTenantView_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoiceView>): Array<InvoiceView> {
    return value.map((x)=>from_candid_InvoiceView_n18(_uploadFile, _downloadFile, x));
}
function to_candid_CreateInvoiceArgs_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateInvoiceArgs): _CreateInvoiceArgs {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceFilter_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceFilter): _InvoiceFilter {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_TenantStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TenantStatus): _TenantStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateInvoiceArgs_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateInvoiceArgs): _UpdateInvoiceArgs {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    issueDate: Timestamp;
    gstEnabled: boolean;
    dueDate: Timestamp;
    patientName: string;
    gstPercentage?: bigint;
    services: Array<ServiceItem>;
}): {
    issueDate: _Timestamp;
    gstEnabled: boolean;
    dueDate: _Timestamp;
    patientName: string;
    gstPercentage: [] | [bigint];
    services: Array<_ServiceItem>;
} {
    return {
        issueDate: value.issueDate,
        gstEnabled: value.gstEnabled,
        dueDate: value.dueDate,
        patientName: value.patientName,
        gstPercentage: value.gstPercentage ? candid_some(value.gstPercentage) : candid_none(),
        services: value.services
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toDate?: Timestamp;
    fromDate?: Timestamp;
    patientName?: string;
}): {
    toDate: [] | [_Timestamp];
    fromDate: [] | [_Timestamp];
    patientName: [] | [string];
} {
    return {
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        patientName: value.patientName ? candid_some(value.patientName) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: InvoiceId;
    issueDate: Timestamp;
    status: InvoiceStatus;
    gstEnabled: boolean;
    dueDate: Timestamp;
    patientName: string;
    gstPercentage?: bigint;
    services: Array<ServiceItem>;
}): {
    id: _InvoiceId;
    issueDate: _Timestamp;
    status: _InvoiceStatus;
    gstEnabled: boolean;
    dueDate: _Timestamp;
    patientName: string;
    gstPercentage: [] | [bigint];
    services: Array<_ServiceItem>;
} {
    return {
        id: value.id,
        issueDate: value.issueDate,
        status: to_candid_InvoiceStatus_n33(_uploadFile, _downloadFile, value.status),
        gstEnabled: value.gstEnabled,
        dueDate: value.dueDate,
        patientName: value.patientName,
        gstPercentage: value.gstPercentage ? candid_some(value.gstPercentage) : candid_none(),
        services: value.services
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TenantStatus): {
    trial: null;
} | {
    active: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    suspended: null;
} {
    return value == TenantStatus.trial ? {
        trial: null
    } : value == TenantStatus.active ? {
        active: null
    } : value == TenantStatus.expired ? {
        expired: null
    } : value == TenantStatus.pending ? {
        pending: null
    } : value == TenantStatus.rejected ? {
        rejected: null
    } : value == TenantStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    cancelled: null;
} | {
    paid: null;
} | {
    sent: null;
} | {
    draft: null;
} {
    return value == InvoiceStatus.cancelled ? {
        cancelled: null
    } : value == InvoiceStatus.paid ? {
        paid: null
    } : value == InvoiceStatus.sent ? {
        sent: null
    } : value == InvoiceStatus.draft ? {
        draft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
